name: Pytest
on: [push, pull_request]
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: pytest-install
        run: make install-test
      - name: pytest
        run: make test